language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "grinfeld-github"
    token:
      secure: "3d7970bd2cc5f292bd2c69dadef6450b243ef21a" # encrypted value of your token
script:
  - gradle sonarqube