micronaut:
  application:
    name: redirect-to-stream
  server:
    port: ${serverPort:8087}

app:
  subscribers:
    size: ${appSubscibers:5}

receiver:
  inactive-url-expire-sec: 300
  global-frequency-count: 10
  global-status: 404
  global-delay-ms: 500
  max-size-of-delayed-requests: 1000