version: '3.1'

services:
  redirect-to-stream:
    container_name: redirect-to-stream
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - "JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -xmx1024m -xms1024m"
      - "JAVA_ARGS=-DserverPort=9876 -DappSubscibers=5"
    ports:
      - "9876:9876"
      - "5005:5005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock